name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      # - name: Set Git user name and email
      #   run: |
      #     git config --global user.name "GitHub Actions"
      #     git config --global user.email "actions@github.com"

      - name: Install dependencies
        run: npm install

      # - name: Create Version Tag
      #   run: npm run release

      - name: Build App
        run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          release_name: Release ${{ github.run_number }}
          tag_name: ${{ github.run_number}}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false

      # - name: Push Changes
      #   run: |
      #     git push --follow-tags