name: Build and Upload Release Artifacts

on:
  push:
    branches:
      - main

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Wait for build to finish
        run: sleep 5

      - name: Create ZIP of dist folder
        run: |
          mkdir -p dist
          zip -r dist/dvz_api.zip dist/

      - name: Upload production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dvz_api
          path: dist/dvz_api.zip


  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install version
        run: npm install --save-dev standard-version

      - name: Set Git user name and email
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create Version Tag
        run: npm run release

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Download zip artifact from the build job
        uses: actions/download-artifact@v4
        with:
          name: dvz_api

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: Release ${{ env.version }}
          body: CHANGELOG.md
          draft: false
          prerelease: false

      # Upload production artifact to release
      - name: Upload production artifact to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dvz_api.zip
          asset_name: dvz_api.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} 

      - name: Push Changes
        run: |
          git push --follow-tags